name: altrad_qr
description: Altrad QR app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  uuid: ^3.0.5
  cupertino_icons: ^1.0.2
  flutter_menu: ^0.4.1
  dropdown_button2: ^1.4.0
  qr_code_scanner: ^1.0.0

  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_analytics: ^10.0.7
  cloud_firestore: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


